language: c
compiler:
  - clang
  - gcc
before_install:
  # Make sure apt is up to date.
  - sudo apt-get update -qq
  # Travis is on 64bit and there will be a cryptic aapt error w/o these libs.
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes ia32-libs ia32-libs-multiarch > /dev/null; fi
  # For native code tests, we need some additional libraries if we are in a 64-bit environment.
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes gcc-multilib > /dev/null; fi
script: cd src && make
